### ISSUE TITLE
Internal server error on login mutation

### ISSUE THREAD

**Issue by this-is-fine-dev** [funkhaus/wp-graphql-cors#11]
try

`mutation MyMutation($login: String!, $password: String!) {
  login(input: {clientMutationId: "", login: $login, password: $password}) {
    status
  }
}`

get

`{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ]
    }
  ],
  "data": {
    "login": null
  }
}`

**Comment by aidnurs** [comment]
I have the same issue. also tried release v1.0.0, no success.
I found it interesting that login works only with admin credentials

**Comment by drewbaker** [comment]
@kidunot89 Take a look at this when you get a moment and invoice me for the time.

**Comment by jacobarriola** [comment]
@kidunot89 my PR (#15) might address this issue. Rather than returning the correct error message (ie 'invalid password'), the server is throwing an error because of an invalid method.

**Comment by drewbaker** [comment]
Fixed with previous commit
