### ISSUE TITLE
Firefox: some cookies are misusing the recommended “SameSite“ attribute

### ISSUE THREAD

**Issue by jacobarriola** [funkhaus/wp-graphql-cors#16]
My console is rendering these warnings. Not sure if this is a configuration issue on my end.

Nothing is broken at the moment. I'm able to login and logout.

>Cookie “_mcnc” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

> Cookie “woocommerce_items_in_cart” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

> Cookie “woocommerce_cart_hash” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Firefox version: 80.0 (Mac)

**Comment by drewbaker** [comment]
This isn’t really something we can control. It’s a wordpress function that I expect they’ll fix in core at some point. You probably get the same message on login of Wordpress via the /wp-admin page too?

https://github.com/funkhaus/wp-graphql-cors/blob/master/includes/login-mutation.php#L65

https://developer.wordpress.org/reference/functions/wp_signon/
