### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by travis-r6s** [funkhaus/wp-graphql-cors#18]
Would it be possible to publish this package to composer, so it can be used with projects like Bedrock?

**Comment by drewbaker** [comment]
@kidunot89 want to do this? I don't use composer.

**Comment by web-programmer-here** [comment]
@drewbaker just checking on this, it would be great to have this feature

**Comment by drewbaker** [comment]
> @drewbaker just checking on this, it would be great to have this feature

I don't really use composer (or PHP much these days really) so I'm the wrong person to do this, but I'm open to a PR for it.

**Comment by web-programmer-here** [comment]
you can just create a `composer.json` in the root of the repo, something like this

```json
{
    "name": "funkhaus/wp-graphql-cors",
    "description": "Makes WP GraphQL's authetication just work. It does this by customizing the CORS headers.",
    "type": "wordpress-plugin",
    "require": {
       "php": "^7.1 || ^8.0",
        "composer/installers": "~1.0"
    }
}
```

if you add this maybe I can test it and see if I can install the plugin using composer

**Comment by drewbaker** [comment]
https://github.com/funkhaus/wp-graphql-cors/pull/36
