### ISSUE TITLE
Login does not work with Chrome (cookies not set/blocked)

### ISSUE THREAD

**Issue by jacobarriola** [funkhaus/wp-graphql-cors#19]
Hey @kidunot89 @drewbaker. The login isn't working for me on Chrome.

Here's the error message Chrome is logging:

>Because a cookie's SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being set in a cross-site context. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery. 
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests

![image](https://user-images.githubusercontent.com/1371573/94378578-6066f800-00df-11eb-9a9a-38f703cf2b9f.png)

## Steps to reproduce:

In Chrome 85, run the following query:

```graphql
mutation {
  loginWithCoookies(clientMutationId: "123" login: "mycoolusername" password: "mycoolpassword") {
    status
    __typename
  }
}
```

Then run a subsequent authenticated query

```graphql
query Me {
  viewer {
    email
    nicename
    __typename
  }
}
```

### Expected results:
1. successful login
```json
{"data":{"loginWithCookies":{"status":"SUCCESS","__typename":"LoginWithCookiesPayload"}}}
```
2. WordPress logged in cookie set (and sent along with subsequent requests)
3. authenticated queries are successful
```json
{"data":{"viewer":{"email":"mycoolemail@something.com","nicename":"jacob","__typename":"User"}}}
```

### Actual results:
1. login is successful
2. cookie was not set and not part of headers on subsequent request
3. authenticated request returns null
```json
{"data":{"viewer":null}}
```
Related to #16

**Comment by drewbaker** [comment]
Curious if you can just login to Wordpress via the regular /wp-login page? 

This plugin doesn’t set any cookies by itself, we just run the regular wp_signon method, this might be a higher up WordPress issue: https://github.com/funkhaus/wp-graphql-cors/blob/master/includes/login-mutation.php#L65

https://developer.wordpress.org/reference/functions/wp_signon/

Also curious what the cookie key is that is causing that error?

**Comment by jacobarriola** [comment]
Thanks for the response, @drewbaker !

>Curious if you can just login to Wordpress via the regular /wp-login page?

Yep, no issues with that.

> This plugin doesn’t set any cookies by itself, we just run the regular wp_signon method, this might be a higher up WordPress.

Yep, I saw that the plugin doesn't explicitly set cookies. Seems like that underlying `wp_signon` method does set an authentication cookie and sends it along in the response headers.

I think the issue is that browsers are becoming stricter with cross-site cookies and they expect certain attributes, otherwise they will be blocked (which is the behavior that I'm seeing in Chrome 85). Reference: https://web.dev/samesite-cookie-recipes/

But yeah, even though the plugin isn't setting the cookie, the core method is try to set the cross-site cookie via the response header, which is getting blocked.

I think we may have to filter the cookie and pass in the `SameSite=None; Secure` attributes that is recommended, although I'm not 100% certain. 

> Also curious what the cookie key is that is causing that error?

Here are the response headers for the `loginWithCookies` mutation.
```
access-control-allow-credentials: true
access-control-allow-headers: Authorization, Content-Type, woocommerce-session
access-control-allow-origin: https://rudis-ecommerce.netlify.app
access-control-expose-headers: woocommerce-session
access-control-max-age: 600
content-encoding: gzip
content-type: application/json; charset=UTF-8
date: Mon, 28 Sep 2020 12:30:52 GMT
server: nginx
set-cookie: wordpress_sec_<RANDOM STRINGS OMITTED FOR PRIVACY>; path=/wp-content/plugins; secure; HttpOnly
set-cookie: wordpress_sec_<RANDOM STRINGS OMITTED FOR PRIVACY>; path=/wp-admin; secure; HttpOnly
set-cookie: wordpress_logged_in_<RANDOM STRINGS OMITTED FOR PRIVACY>; path=/; secure; HttpOnly
set-cookie: _mcnc=1; Max-Age=2; Path=/
status: 200
vary: Accept-Encoding
x-content-type-options: nosniff
x-hacker: If you're reading this, you should visit github.com/wp-graphql and contribute!
x-robots-tag: noindex
```

**Comment by drewbaker** [comment]
Do you have your frontend domain set in the CORS options panel?

**Comment by jacobarriola** [comment]
Here's a screenshot of my settings.

![image](https://user-images.githubusercontent.com/1371573/94437234-5205f400-0152-11eb-98c1-8025b02bbd82.png)

**Comment by jonshipman** [comment]
The issue is with wp_set_auth_cookie. I have a fix that works. I'll see if I can pull request something in. Looks like there's an issue on trac for the WordPress core. See: https://core.trac.wordpress.org/ticket/37000.

**Comment by ardiewen** [comment]
just wanted to comment that i was having the same issue as @jacobarriola while testing on a fresh install and applying the PR that @jonshipman added in #20 seems to have fixed the issue.

**Comment by drewbaker** [comment]
Fixed with #20

**Comment by sigfrid86** [comment]
I have the same problem with chrome and safari. (firefox works well
![Captura de Pantalla 2022-03-13 a la(s) 6 26 07 p m](https://user-images.githubusercontent.com/5641791/158086273-dfa63b45-1bd1-4de4-87b4-b13f3aa05a37.png)
)

**Comment by drewbaker** [comment]
This is because of same-site cookie settings with the default wordpress login functions.

This might help:
https://github.com/MikhailRoot/samesite-cookie-manager

The move would be to port in functions from that plugin into this one to make sure cookies get set with the correct domains.
