### ISSUE TITLE
Send site credentials problem with newer version of the plugin

### ISSUE THREAD

**Issue by zamson** [funkhaus/wp-graphql-cors#21]
Im getting this error: `The 'Access-Control-Allow-Origin' header cannot be wildcard when using send site credentials`. It's working with 1.0 of the plugin but not with newer versions. I've tried changing the settings but it still won't work. Had to downgrade for now. My domains are mapped in the allowed list.

Any ideas?

**Comment by drewbaker** [comment]
This is an upstream WordPress issue. I just merged in a PR that fixes this though. Once WP updates I'll have to remove it, but it shouldn't effect your use of the plugin.
