### ISSUE TITLE
Authorized domains list not working ( next.js app )

### ISSUE THREAD

**Issue by vstrelianyi** [funkhaus/wp-graphql-cors#22]
I'm developing a next.js app with WP backend locally and I have faced the following issue - 
1) after activating the plugin next.js build returns an error as expected - it cannot fetch data via GraphQl
2) a have added http://localhost:3000/ and http://localhost to the authorized domains list -> next.js still can't fetch data - that is unexpected behaviour

**Comment by drewbaker** [comment]
Are you sending the cookies with your request?

See #3 here: https://github.com/funkhaus/wp-graphql-cors#installation

**Comment by vstrelianyi** [comment]
> Are you sending the cookies with your request?
> 
> See #3 here: https://github.com/funkhaus/wp-graphql-cors#installation

- I'm not sending any cookies
- I have configured apollo to send: credentials = "include" - as was explained in the instructions
- I'm sending headers -> Access-Control-Allow-Origin: true

my code:
const link = createHttpLink( {
  uri: uri,
  credentials: 'include',
  headers: {
    'Access-Control-Allow-Origin': true,
  },
} );

**Comment by drewbaker** [comment]
Do you have a codesandbox we can check out? Because this has come up a bunch in the past and it’s always been that frontend wasn’t sending the cookies (which is what credentials:true is doing). 

If you look at your network inspector for a client side request, you should be able to see if your request is passing along the default wp cookies. This should help you debug.

**Comment by Marco-Daniel** [comment]
Running into the same issue, setting credentials to include in apollo client doesn't seem to send any cookies after checking the network inspector

**Comment by vstrelianyi** [comment]
> Do you have a codesandbox we can check out? Because this has come up a bunch in the past and it’s always been that frontend wasn’t sending the cookies (which is what credentials:true is doing).
> 
> If you look at your network inspector for a client side request, you should be able to see if your request is passing along the default wp cookies. This should help you debug.

I will add my project to codesandbox  and will let you know!

**Comment by vstrelianyi** [comment]
> Do you have a codesandbox we can check out? Because this has come up a bunch in the past and it’s always been that frontend wasn’t sending the cookies (which is what credentials:true is doing).
> 
> If you look at your network inspector for a client side request, you should be able to see if your request is passing along the default wp cookies. This should help you debug.

Here is the public project on codesandbox
https://codesandbox.io/s/20210110sidegigzpublic-uye9l?file=/.gitignore

apollo config path:
frontend->src->apollo->client.js

**Comment by ebisLab** [comment]
> > Do you have a codesandbox we can check out? Because this has come up a bunch in the past and it’s always been that frontend wasn’t sending the cookies (which is what credentials:true is doing).
> > If you look at your network inspector for a client side request, you should be able to see if your request is passing along the default wp cookies. This should help you debug.
> 
> Here is the public project on codesandbox
> https://codesandbox.io/s/20210110sidegigzpublic-uye9l?file=/.gitignore
> 
> apollo config path:
> frontend->src->apollo->client.js

did you ever get it to work ?

**Comment by drewbaker** [comment]
Pushed a new version that fixes a lot of these issues I think
