### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ebisLab** [funkhaus/wp-graphql-cors#23]
Hi , I dont understand how to install this plug in, it mentions to make sure WPGraphql is installed. But where do I get the plug in and where do I put it ?

**Comment by w3bdesign** [comment]
First download a .zip of the plugin in Github, then in Wordpress admin go to Plugins -> Add New -> Upload Plugin and choose the .zip file.
Then remember to activate it.

**Comment by ebisLab** [comment]
Wonderful, it worked! The directions confused me a bit. 
Okay, this is what I have in my settings. Is it right ? I'm still getting the error in my frontend 

![screencapture-woo-me-ebislab-wp-wp-admin-options-general-php-2021-03-01-08_29_36](https://user-images.githubusercontent.com/43076235/109503458-4c496d00-7a68-11eb-94ea-6143b463ae35.png)

<img width="557" alt="Screen Shot 2021-03-01 at 8 33 15 AM" src="https://user-images.githubusercontent.com/43076235/109503987-f2957280-7a68-11eb-9287-8925e7dd68cf.png">

**Comment by w3bdesign** [comment]
@ebisLab 

Would help if you provided more information about what you are trying to accomplish with your code. 
Are you trying to login? Are you working on an eCommerce solution with WP? Etc.

**Comment by ebisLab** [comment]
ecommerce solution with WP. 
Currently testing out my frontend in dev mode locally hence the localhost8181, trying to allow the localhost to be one of those allowed url, where it can fetch the /graphql endpoint safely

**Comment by w3bdesign** [comment]
Most likely it is a code issue and not a plugin issue.

Could you share the code you are using to send the headers to WordPress?

**Comment by ebisLab** [comment]
sure thing

```javascript
const client = new ApolloClient({

	ssrMode: typeof window === 'undefined',

		link: middleware.concat( afterware.concat( createHttpLink({

			uri:`${process.env.NEXT_PUBLIC_WORDPRESS_URL}/graphql`,

			credentials: 'include',

			headers: {

				'Access-Control-Allow-Origin': '*',

			// 	"Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept",

				},

	}) ) ),
```

**Comment by w3bdesign** [comment]
Based on the code I see so far, it looks like you are not sending the woocommerce-session token in the header. That may be the reason if you are building an eCommerce solution with WP and WooCommerce.

I have built an eCommerce solution myself with WooCommerce and Apollo, you may take a look at https://github.com/w3bdesign/nextjs-woocommerce/blob/master/utils/apollo/ApolloClient.js and https://github.com/w3bdesign/nextjs-woocommerce to see how I did it, and let me know if you need any help understanding my code.
