### ISSUE TITLE
Still get cors issues after using WP Graphql Cors

### ISSUE THREAD

**Issue by gabriel-nack** [funkhaus/wp-graphql-cors#28]
Hi,
We are using WP Graphql and Apollo to fetch data from WordPress in our Next.js codebase. Recently we've tried using your plugin WP Graphql Cors in order to try to get rid of some cors issues we experienced on some queries. 

However it does not seem to work even though we enter the origins we want to allow in WP admin and the "credentials": "inlcude" settings in ApolloClient. We've tried changing to run graphql queries with ApolloServer which resolves the issue, but that adds a lot of extra work and complexitiy for us in other ways that we would prefer to avoid. One of the wpgraphql mutations that fails due to cors is addToCart. 

The console error is _"... has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."_ We tried to use the no-cors option but that gives us further errors and is not a secure solution. We also tried adding cors settings in the htaccess file in WP codebase, but that throws us more fetch errors.

Would kindly appreciate all the help and guidance we can get on this.

**Comment by tBorbas** [comment]
same goes for me, but as far as I see this plugin is full of holes...

**Comment by city17** [comment]
Similar problem here with a NextJS application. Did you find any solutions @gabriel-nack ?

**Comment by drewbaker** [comment]
Have you got Apollo setup to send cookies with the request?

**Comment by mhadaily** [comment]
Same here, I still have cors Issue even though I enabled this plugin

**Comment by drewbaker** [comment]
Can you provide a code sandbox of your frontend code? 

The way to troubleshoot this is look in your network inspector and make sure that you are sending cookies in the request.

**Comment by gabriel-nack** [comment]
> Similar problem here with a NextJS application. Did you find any solutions @gabriel-nack ?

This was a while back ago, but I believed I solved it by using Next.js api routes in pages/api instead of custom routes

**Comment by maximilliangeorge** [comment]
I never got this to work. Tried a bunch of stuff, but in the end simply adding to `header('Access-Control-Allow-Origin: http://localhost:3000');` in wp-config.php was the only thing that worked.
