### ISSUE TITLE
allowed origin issues

### ISSUE THREAD

**Issue by oskarmodig** [funkhaus/wp-graphql-cors#29]
We're having issues with `Access-Control-Allow-Origin`. We have it setup to block unauthorized domains, and have added 2 authorized domains.

Despite this `Access-Control-Allow-Origin` is sent as `"*"`. When unchecking "Block unauthorized domains" `Access-Control-Allow-Origin` becomes `siteurl`.

I've found 2 reasons for this. First, the check for "Block unauthorized domains" in _\includes\process-request.php_ is like this: 

```
elseif ( 'on' === get_graphql_setting( 'acao_block_unauthorized', 'off', 'graphql_cors_settings' ) ) {
	$headers['Access-Control-Allow-Origin'] = '*';
}
```

If I'm not mistaken it means that if the block is on, everyone is allowed.

Our next problem is that `$_SERVER['HTTP_REFERER']` isn't set for us, so the check in `wpgraphql_cors_is_allowed_origin()` fails.

**Comment by drewbaker** [comment]
Closed with #30
