### ISSUE TITLE
registerUser mutation and secure cookies

### ISSUE THREAD

**Issue by ardiewen** [funkhaus/wp-graphql-cors#31]
The default behaviour of the  `registerUser` mutation from `wp-graphql` includes setting the current user to the one that was just successfully registered, [as seen here](https://github.com/wp-graphql/wp-graphql/blob/cb24c85ac655664cdbdefa0e7506401ae4abc73b/src/Mutation/UserRegister.php#L117-L125).

However, when using this in conjunction with `wp-graphql-cors`, we cannot set the response cookie because the default `registerUser` mutation doesn't set a secure cookie.

Here's an example of some response headers from a registerUser mutation:
![image](https://user-images.githubusercontent.com/39966887/131847754-778923d9-26c9-4809-895e-2dad8535b155.png)

The yellow warning message next to each set-cookie response header reads:
> This Set-Cookie didn't specify a "SameSite" attribute and was default to "SameSite=Lax", and was blocked because it came from a cross-site response which was not the response to a top-level navigation. The Set-Cookie had to have been set with "SameSite=None" to enable cross-site usage.
 
Hoping to have a discussion on what a potential solution would be, such as:

1) Create a `registerWithCookies` mutation similar to `loginWithCookies`?
2) Implement something on the Wordpress End?
3) Something else?

Note: Also an edge case, but `wp-graphql-woocommerce` has the ability to register users using the checkout mutation as well. This presents the same issue as the `registerUser` mutation.

**Comment by drewbaker** [comment]
Yeah the WordPress core functions around setting cookies has a really poor API (last time I checked). So we had to just make our own login functions to set a cookie (here: https://github.com/funkhaus/wp-graphql-cors/blob/master/includes/set-auth-cookie.php)

I think the `registerWithCookies` approach would be best, until core gets some sort of better cookie or auth API.

**Comment by drewbaker** [comment]
I wonder if this helps? https://wordpress.org/plugins/samesite/

**Comment by drewbaker** [comment]
Can you try installing this plugin and see if it works?

[samesite-cookie-manager-master.zip](https://github.com/funkhaus/wp-graphql-cors/files/7100914/samesite-cookie-manager-master.zip)

**Comment by ardiewen** [comment]
@drewbaker yep that works, nice one!
