### ISSUE TITLE
No cookies are added. What is the expected result with this plugin?

### ISSUE THREAD

**Issue by dnspnjrs** [funkhaus/wp-graphql-cors#32]
Hi there, I cant seem to make this plugin working. I'm primarily looking for a solution to preview post drafts on Nextjs. I'm a beginner regarding to setting cookies in wordpress.

1. I've installed the plugin and added the settings as shown.
2. I'm using apollo in nextjs to query a draft page
3. The draft returns null, but when the same page is not a draft it returns correctly.

Am I correct to assume that this plugin will add cookies and allowing a query from the given domain in the settings?

**Comment by drewbaker** [comment]
Did you get this working?

If you login to Wordpress, and your frontend sends cookies with the request, then you'll get back "draft" posts.
