### ISSUE TITLE
Unable to activate plugin : Trailing comma cause fatal error

### ISSUE THREAD

**Issue by vdilly** [funkhaus/wp-graphql-cors#33]
Installing this plugin release 2.0 cause fatal error when activated in Wordpress because of this comma : 
![image](https://user-images.githubusercontent.com/41357661/146020000-03256f46-51ff-47d5-b67b-c67c1d36ec5e.png)

In file : 
\wp-content\plugins\wp-graphql-cors-2.0\includes\admin\admin.php

**Comment by itrigger** [comment]
i fix it like this
array_merge(\WPGraphQL\CORS\Settings\Access::get_fields(), \WPGraphQL\CORS\Settings\Cookies::get_fields())

**Comment by drewbaker** [comment]
Weird. What version of PHP were you running?

**Comment by vdilly** [comment]
> Weird. What version of PHP were you running?

7.2.34
Just to be clear :  removing the comma did the trick
