### ISSUE TITLE
Block unauthorized domains not working

### ISSUE THREAD

**Issue by dandin84** [funkhaus/wp-graphql-cors#34]
Hi, I am trying to block unauthorized domains so only specific domain will have the option to fetch data. I tried several configurations options but none of them got me the right result - but I still succeed to fetch data via Postman.  I only want to block unauthorized domains without the need of user authentication.

What am I doing wrong? Thanks!

![image](https://user-images.githubusercontent.com/6383184/150034899-24e931a6-d364-4499-9ccd-b1277a97a9b1.png)

**Comment by drewbaker** [comment]
Hello! It's been a long time since I used that feature. This is the function that should block domains: https://github.com/funkhaus/wp-graphql-cors/blob/master/includes/process-request.php#L153

**Comment by dandin84** [comment]
Hi and thanks for your reply! I saw the function and I guess there is an issue with it. I wanted to be sure that I used it correctly. I will debug it and try to make it work.

**Comment by drewbaker** [comment]
Closed as I think this was fixed previously. Please comment and I will reopen if this is still an issue.

**Comment by drewbaker** [comment]
Closed as I think this was fixed previously. Please comment and I will reopen if this is still an issue.
