### ISSUE TITLE
loginWithCookies mutation not working

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/wp-graphql-cors#37]
Apparently the `loginWithCookies` mutation doesn't set cookies correctly. I suspect it is a SameSite issue.

**Comment by drewbaker** [comment]
This is because the default WordPress login functions don't handle samesite, so we will have to build our own cookie setters, like in the fuxt-backend boilerplate I suspect.

**Comment by jaymeedwards** [comment]
Hey @drewbaker . I've been trying to get this working and I would love any insight you have.

In a fork, I fixed some code paths that were causing the "secure" cookie attribute to get set when running on HTTP localhost. Once I did that part, everything works great locally.

However once I tried the same up in the cloud via HTTPS, the cookies look correct via chrome dev tools, but wordpress acts as though the user isn't logged in. I can't for the life of me figure out why the difference in behavior exists between the two. I added a config setting for toggling between the three samesite modes to see if it would help any but it doesn't seem to.

The fork I'm working with is here: https://github.com/eavonius/wp-graphql-cors

**Comment by jaymeedwards** [comment]
There may be other issues, but for posterity of closing the loop on my earlier comment, I addressed at least the issues for my site in #38

**Comment by cfab** [comment]
Any news on this ;-) ?

**Comment by drewbaker** [comment]
We added the ability to set the `sameSite` option into our theme, if anyone is curious.

https://github.com/funkhaus/fuxt-backend/blob/master/functions/cookie-manager.php
