### ISSUE TITLE
Getting Apollo error on SSR for CORS requests

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/wp-graphql-cors#5]
I don't have much data for this as it's hard to debug, but when making a request to WP-GQL for data that would require a cookie, I get a server side error, but then the data does display client side.

![Screen Shot 2019-12-06 at 3 23 17 PM](https://user-images.githubusercontent.com/475015/70363222-692eca80-183c-11ea-899e-c7735364474a.png)

**Comment by drewbaker** [comment]
Figured out more what is going on here. Updated to latest version, not get all sorts of errors when trying to preview a Post that is drafted.

![Screen Shot 2019-12-21 at 8 19 21 PM](https://user-images.githubusercontent.com/475015/71317021-3c2f0a00-242f-11ea-8953-c8272cc25a4e.png)

**Comment by kidunot89** [comment]
Is `Send site credentials` check? If not, you'll get a CORS errors on the client when the `credentials` fetch options is set to `include`. You also won't receive any cookies, if `Send site credentials` is not checked.
