### ISSUE TITLE
Login Mutation ends in internal server error

### ISSUE THREAD

**Issue by henrikwirth** [funkhaus/wp-graphql-cors#8]
When I activate the login mutation and query like so:

```
mutation LoginUser($input: LoginInput!) {
  login(input: $input) {
    status
  }
}
```

I end up getting an internal server error:

```
{
  "error": {
    "errors": [
      {
        "debugMessage": "You cannot register duplicate fields on the same Type. The field 'login' already exists on the type 'rootMutation'. Make sure to give the field a unique name.",
        "message": "Internal server error",
        "category": "internal"
      }
    ]
  }
}
```

There already is a login mutation from WPGraphQL, so this is a bit confusing.

Also when I set `credentials: 'include'` it works if I set the allowed Domains to my localhost, but it doesn't set any Cookies.

**Comment by drewbaker** [comment]
@henrikwirth I made a lot of updates to this yesterday, update your version to the latest. You will need `credentials: 'include'` set.

**Comment by kidunot89** [comment]
My bad :man_facepalming: I'll fixed it immediately
